### ISSUE TITLE
C:\Projects should not exist

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor-tests/build-tests#3]

**Comment by OwenMcDonnell** [comment]
Testing for the existence of C:\Projects folder before clone of remote repository.

Repository: https://github.com/appveyor-tests/c-projects-folder-should-not-exist
Project: [![Build status](https://ci.appveyor.com/api/projects/status/t1msvc6ulkaojq27?svg=true)](https://ci.appveyor.com/project/appveyor-tests/c-projects-folder-should-not-exist)

**Comment by FeodorFitsner** [comment]
Well, actually, the thing is `c:\Projects` will always exist, even in `init` phase.

What we'd really like to test here is that `c:\projects` is all lowercase, not starting with capital `P`.

**Comment by IlyaFinkelshteyn** [comment]
My fault. I told Owen it should not exist. This can be used easily in PS: "[System.String]::Equals("C:\Projects", "C:\projects")"

**Comment by OwenMcDonnell** [comment]
Oh sorry, wasn't paying attention to this thread. I fixed it i think, but not the way Ilya suggested. Maybe your way is better?

**Comment by IlyaFinkelshteyn** [comment]
You way is great :)
