### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor-tests/build-tests#5]

**Comment by OwenMcDonnell** [comment]
Repository: https://github.com/appveyor-tests/npm-install/blob/master/appveyor.yml
Project: [![Build status](https://ci.appveyor.com/api/projects/status/gs1gv580ui3hjtwr?svg=true)](https://ci.appveyor.com/project/appveyor-tests/npm-install)

**Comment by FeodorFitsner** [comment]
Assigned to [Tender discussion #16](http://help.appveyor.com/discussions/support/16-test-from-tender).
